version: 2
jobs:
  test:
    working_directory: /go/src/github.com/timstott/forward
    docker:
      - image: circleci/golang:1
    environment:
    steps:
      - checkout
      - run: bin/test

workflows:
  version: 2
  build:
    jobs:
      - test
